// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'registry_session.freezed.dart';

class ClientSessionEntity {
  /// The URL of the homeserver of the user.
  final String homeserver;

  /// The path of the database.
  final String sessionPath;

  /// The passphrase of the database.
  final String passphrase;

  const ClientSessionEntity({
    required this.homeserver,
    required this.sessionPath,
    required this.passphrase,
  });

  @override
  int get hashCode =>
      homeserver.hashCode ^ sessionPath.hashCode ^ passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientSessionEntity &&
          runtimeType == other.runtimeType &&
          homeserver == other.homeserver &&
          sessionPath == other.sessionPath &&
          passphrase == other.passphrase;
}

@freezed
sealed class Credentials with _$Credentials {
  const Credentials._();

  const factory Credentials.accessToken(String field0) =
      Credentials_AccessToken;
  const factory Credentials.userPassword({
    required String username,
    required String password,
  }) = Credentials_UserPassword;
}

class MatrixSessionEntity {
  /// The data to re-build the client.
  final ClientSessionEntity clientSession;

  /// The Matrix user session.
  final UserSessionEntity? userSession;

  /// The latest sync token.
  ///
  /// It is only needed to persist it when using `Client::sync_once()` and we
  /// want to make our syncs faster by not receiving all the initial sync
  /// again.
  final String? syncToken;
  final Credentials? credentials;

  const MatrixSessionEntity({
    required this.clientSession,
    this.userSession,
    this.syncToken,
    this.credentials,
  });

  @override
  int get hashCode =>
      clientSession.hashCode ^
      userSession.hashCode ^
      syncToken.hashCode ^
      credentials.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixSessionEntity &&
          runtimeType == other.runtimeType &&
          clientSession == other.clientSession &&
          userSession == other.userSession &&
          syncToken == other.syncToken &&
          credentials == other.credentials;
}

class UserSessionEntity {
  final String accessToken;
  final String? refreshToken;
  final String deviceId;
  final String matrixUserId;

  const UserSessionEntity({
    required this.accessToken,
    this.refreshToken,
    required this.deviceId,
    required this.matrixUserId,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      refreshToken.hashCode ^
      deviceId.hashCode ^
      matrixUserId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSessionEntity &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          deviceId == other.deviceId &&
          matrixUserId == other.matrixUserId;
}
