// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RoomEntity {
  final String roomId;
  final String displayName;
  final String? avatarUrl;
  final String? lastEventText;
  final DateTime? lastEventReceivedTime;
  final bool isDirectChat;
  final bool isEncrypted;
  final String? lastEvent;
  final int participantCount;

  const RoomEntity({
    required this.roomId,
    required this.displayName,
    this.avatarUrl,
    this.lastEventText,
    this.lastEventReceivedTime,
    required this.isDirectChat,
    required this.isEncrypted,
    this.lastEvent,
    required this.participantCount,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      lastEventText.hashCode ^
      lastEventReceivedTime.hashCode ^
      isDirectChat.hashCode ^
      isEncrypted.hashCode ^
      lastEvent.hashCode ^
      participantCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomEntity &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          lastEventText == other.lastEventText &&
          lastEventReceivedTime == other.lastEventReceivedTime &&
          isDirectChat == other.isDirectChat &&
          isEncrypted == other.isEncrypted &&
          lastEvent == other.lastEvent &&
          participantCount == other.participantCount;
}
