// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -655152125;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__okra_wrap__fetch_room_events_by_room_id_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "fetch_room_events_by_room_id", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_room_id = <String>::sse_decode(&mut deserializer);
let api_account_id = <String>::sse_decode(&mut deserializer);
let api_sink = <StreamSink<Vec<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>,flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::api::okra_wrap::fetch_room_events_by_room_id(api_room_id, api_account_id, api_sink).await?;   Ok(output_ok)
                    })().await)
                } })
}
fn wire__crate__api__okra_wrap__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::okra_wrap::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__okra_wrap__register_matrix_client_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "register_matrix_client", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session = <crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::api::okra_wrap::register_matrix_client(api_session).await?;   Ok(output_ok)
                    })().await)
                } })
}
fn wire__crate__api__okra_wrap__sync_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_account_id = <String>::sse_decode(&mut deserializer);
            let api_sink =
                <StreamSink<String, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
                    &mut deserializer,
                );
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::okra_wrap::sync_events(api_account_id, api_sink).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__okra_wrap__sync_rooms_by_space_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_rooms_by_space",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_space_id = <String>::sse_decode(&mut deserializer);
            let api_account_id = <String>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                Vec<crate::features::rooms::domain::entities::room::RoomEntity>,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::okra_wrap::sync_rooms_by_space(
                            api_space_id,
                            api_account_id,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__okra_wrap__tick_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tick",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink =
                <StreamSink<i32, flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(
                    &mut deserializer,
                );
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::okra_wrap::tick(api_sink)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for chrono::DateTime<chrono::Utc> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i64>::sse_decode(deserializer);
        return chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(
            chrono::DateTime::from_timestamp_micros(inner)
                .expect("invalid or out-of-range datetime")
                .naive_utc(),
            chrono::Utc,
        );
    }
}

impl SseDecode for std::collections::HashMap<String, String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<(String, String)>>::sse_decode(deserializer);
        return inner.into_iter().collect();
    }
}

impl SseDecode for StreamSink<String, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for StreamSink<i32, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        Vec<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        Vec<crate::features::rooms::domain::entities::room::RoomEntity>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_homeserver = <String>::sse_decode(deserializer);
let mut var_sessionPath = <String>::sse_decode(deserializer);
let mut var_passphrase = <String>::sse_decode(deserializer);
return crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity{homeserver: var_homeserver, session_path: var_sessionPath, passphrase: var_passphrase};}
                }

impl SseDecode
    for crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::AccessToken(var_field0);
            }
            1 => {
                let mut var_username = <String>::sse_decode(deserializer);
                let mut var_password = <String>::sse_decode(deserializer);
                return crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::UserPassword{username: var_username, password: var_password};
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode
    for crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_value =
                    <crate::features::timeline::domain::entities::event::EventEntity>::sse_decode(
                        deserializer,
                    );
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushFront{value: var_value};
            }
            1 => {
                let mut var_value =
                    <crate::features::timeline::domain::entities::event::EventEntity>::sse_decode(
                        deserializer,
                    );
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushBack{value: var_value};
            }
            2 => {
                let mut var_index = <u32>::sse_decode(deserializer);
                let mut var_value =
                    <crate::features::timeline::domain::entities::event::EventEntity>::sse_decode(
                        deserializer,
                    );
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Insert{index: var_index, value: var_value};
            }
            3 => {
                let mut var_index = <u32>::sse_decode(deserializer);
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Remove{index: var_index};
            }
            4 => {
                let mut var_index = <u32>::sse_decode(deserializer);
                let mut var_value =
                    <crate::features::timeline::domain::entities::event::EventEntity>::sse_decode(
                        deserializer,
                    );
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Update{index: var_index, value: var_value};
            }
            5 => {
                let mut var_items = <Vec<
                    crate::features::timeline::domain::entities::event::EventEntity,
                >>::sse_decode(deserializer);
                return crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Reset{items: var_items};
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::features::timeline::domain::entities::event::EventEntity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_senderId = <String>::sse_decode(deserializer);
        let mut var_senderDisplayName = <Option<String>>::sse_decode(deserializer);
        let mut var_senderAvatarUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_formattedContent = <Option<String>>::sse_decode(deserializer);
        let mut var_timestamp = <Option<chrono::DateTime<chrono::Utc>>>::sse_decode(deserializer);
        let mut var_isRedacted = <bool>::sse_decode(deserializer);
        let mut var_eventType = <String>::sse_decode(deserializer);
        let mut var_messageType = <String>::sse_decode(deserializer);
        let mut var_status = <String>::sse_decode(deserializer);
        let mut var_isEncrypted = <bool>::sse_decode(deserializer);
        let mut var_fileInfo =
            <Option<std::collections::HashMap<String, String>>>::sse_decode(deserializer);
        return crate::features::timeline::domain::entities::event::EventEntity {
            id: var_id,
            sender_id: var_senderId,
            sender_display_name: var_senderDisplayName,
            sender_avatar_url: var_senderAvatarUrl,
            content: var_content,
            formatted_content: var_formattedContent,
            timestamp: var_timestamp,
            is_redacted: var_isRedacted,
            event_type: var_eventType,
            message_type: var_messageType,
            status: var_status,
            is_encrypted: var_isEncrypted,
            file_info: var_fileInfo,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode
    for Vec<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::features::timeline::domain::entities::event::EventEntity> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::features::timeline::domain::entities::event::EventEntity>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<(String, String)>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::features::rooms::domain::entities::room::RoomEntity> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::features::rooms::domain::entities::room::RoomEntity>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_clientSession = <crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity>::sse_decode(deserializer);
let mut var_userSession = <Option<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity>>::sse_decode(deserializer);
let mut var_syncToken = <Option<String>>::sse_decode(deserializer);
let mut var_credentials = <Option<crate::features::matrix_client_registry::domain::entities::registry_session::Credentials>>::sse_decode(deserializer);
return crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity{client_session: var_clientSession, user_session: var_userSession, sync_token: var_syncToken, credentials: var_credentials};}
                }

impl SseDecode for Option<std::collections::HashMap<String, String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<std::collections::HashMap<String, String>>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<chrono::DateTime<chrono::Utc>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<chrono::DateTime<chrono::Utc>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode
    for Option<
        crate::features::matrix_client_registry::domain::entities::registry_session::Credentials,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::features::matrix_client_registry::domain::entities::registry_session::Credentials>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }

impl SseDecode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        let mut var_field1 = <String>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::features::rooms::domain::entities::room::RoomEntity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_roomId = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_avatarUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_lastEventText = <Option<String>>::sse_decode(deserializer);
        let mut var_lastEventReceivedTime =
            <Option<chrono::DateTime<chrono::Utc>>>::sse_decode(deserializer);
        let mut var_isDirectChat = <bool>::sse_decode(deserializer);
        let mut var_isEncrypted = <bool>::sse_decode(deserializer);
        let mut var_lastEvent = <Option<String>>::sse_decode(deserializer);
        let mut var_participantCount = <i32>::sse_decode(deserializer);
        return crate::features::rooms::domain::entities::room::RoomEntity {
            room_id: var_roomId,
            display_name: var_displayName,
            avatar_url: var_avatarUrl,
            last_event_text: var_lastEventText,
            last_event_received_time: var_lastEventReceivedTime,
            is_direct_chat: var_isDirectChat,
            is_encrypted: var_isEncrypted,
            last_event: var_lastEvent,
            participant_count: var_participantCount,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_accessToken = <String>::sse_decode(deserializer);
let mut var_refreshToken = <Option<String>>::sse_decode(deserializer);
let mut var_deviceId = <String>::sse_decode(deserializer);
let mut var_matrixUserId = <String>::sse_decode(deserializer);
return crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity{access_token: var_accessToken, refresh_token: var_refreshToken, device_id: var_deviceId, matrix_user_id: var_matrixUserId};}
                }

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__okra_wrap__fetch_room_events_by_room_id_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__okra_wrap__init_app_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__okra_wrap__register_matrix_client_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__okra_wrap__sync_events_impl(port, ptr, rust_vec_len, data_len),
        5 => {
            wire__crate__api__okra_wrap__sync_rooms_by_space_impl(port, ptr, rust_vec_len, data_len)
        }
        6 => wire__crate__api__okra_wrap__tick_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.homeserver.into_into_dart().into_dart(),
self.session_path.into_into_dart().into_dart(),
self.passphrase.into_into_dart().into_dart()
                ].into_dart()
                }
            }
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {}
impl flutter_rust_bridge::IntoIntoDart<crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity> for crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {
            fn into_into_dart(self) -> crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::AccessToken(field0) => { [0.into_dart(),
field0.into_into_dart().into_dart()].into_dart() }
crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::UserPassword{username,password} => { [1.into_dart(),
username.into_into_dart().into_dart(),
password.into_into_dart().into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::features::matrix_client_registry::domain::entities::registry_session::Credentials,
    > for crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
{
    fn into_into_dart(
        self,
    ) -> crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
    {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushFront{value} => { [0.into_dart(),
value.into_into_dart().into_dart()].into_dart() }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushBack{value} => { [1.into_dart(),
value.into_into_dart().into_dart()].into_dart() }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Insert{index,value} => { [2.into_dart(),
index.into_into_dart().into_dart(),
value.into_into_dart().into_dart()].into_dart() }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Remove{index} => { [3.into_dart(),
index.into_into_dart().into_dart()].into_dart() }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Update{index,value} => { [4.into_dart(),
index.into_into_dart().into_dart(),
value.into_into_dart().into_dart()].into_dart() }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Reset{items} => { [5.into_dart(),
items.into_into_dart().into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity,
    > for crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity
{
    fn into_into_dart(
        self,
    ) -> crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::features::timeline::domain::entities::event::EventEntity
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.sender_id.into_into_dart().into_dart(),
            self.sender_display_name.into_into_dart().into_dart(),
            self.sender_avatar_url.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.formatted_content.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
            self.is_redacted.into_into_dart().into_dart(),
            self.event_type.into_into_dart().into_dart(),
            self.message_type.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.is_encrypted.into_into_dart().into_dart(),
            self.file_info.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::features::timeline::domain::entities::event::EventEntity
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::features::timeline::domain::entities::event::EventEntity,
    > for crate::features::timeline::domain::entities::event::EventEntity
{
    fn into_into_dart(self) -> crate::features::timeline::domain::entities::event::EventEntity {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.client_session.into_into_dart().into_dart(),
self.user_session.into_into_dart().into_dart(),
self.sync_token.into_into_dart().into_dart(),
self.credentials.into_into_dart().into_dart()
                ].into_dart()
                }
            }
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {}
impl flutter_rust_bridge::IntoIntoDart<crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity> for crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {
            fn into_into_dart(self) -> crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::features::rooms::domain::entities::room::RoomEntity {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.room_id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.avatar_url.into_into_dart().into_dart(),
            self.last_event_text.into_into_dart().into_dart(),
            self.last_event_received_time.into_into_dart().into_dart(),
            self.is_direct_chat.into_into_dart().into_dart(),
            self.is_encrypted.into_into_dart().into_dart(),
            self.last_event.into_into_dart().into_dart(),
            self.participant_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::features::rooms::domain::entities::room::RoomEntity
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::features::rooms::domain::entities::room::RoomEntity>
    for crate::features::rooms::domain::entities::room::RoomEntity
{
    fn into_into_dart(self) -> crate::features::rooms::domain::entities::room::RoomEntity {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.access_token.into_into_dart().into_dart(),
self.refresh_token.into_into_dart().into_dart(),
self.device_id.into_into_dart().into_dart(),
self.matrix_user_id.into_into_dart().into_dart()
                ].into_dart()
                }
            }
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {}
impl flutter_rust_bridge::IntoIntoDart<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity> for crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {
            fn into_into_dart(self) -> crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {
                self
            }
        }

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for chrono::DateTime<chrono::Utc> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.timestamp_micros(), serializer);
    }
}

impl SseEncode for std::collections::HashMap<String, String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<(String, String)>>::sse_encode(self.into_iter().collect(), serializer);
    }
}

impl SseEncode for StreamSink<String, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for StreamSink<i32, flutter_rust_bridge::for_generated::SseCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        Vec<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        Vec<crate::features::rooms::domain::entities::room::RoomEntity>,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.homeserver, serializer);
<String>::sse_encode(self.session_path, serializer);
<String>::sse_encode(self.passphrase, serializer);}
                }

impl SseEncode
    for crate::features::matrix_client_registry::domain::entities::registry_session::Credentials
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::AccessToken(field0) => { <i32>::sse_encode(0, serializer); <String>::sse_encode(field0, serializer);
 }
crate::features::matrix_client_registry::domain::entities::registry_session::Credentials::UserPassword{username,password} => { <i32>::sse_encode(1, serializer); <String>::sse_encode(username, serializer);
<String>::sse_encode(password, serializer);
 }
 _ => { unimplemented!(""); }}
    }
}

impl SseEncode
    for crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushFront{value} => { <i32>::sse_encode(0, serializer); <crate::features::timeline::domain::entities::event::EventEntity>::sse_encode(value, serializer);
 }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::PushBack{value} => { <i32>::sse_encode(1, serializer); <crate::features::timeline::domain::entities::event::EventEntity>::sse_encode(value, serializer);
 }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Insert{index,value} => { <i32>::sse_encode(2, serializer); <u32>::sse_encode(index, serializer);
<crate::features::timeline::domain::entities::event::EventEntity>::sse_encode(value, serializer);
 }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Remove{index} => { <i32>::sse_encode(3, serializer); <u32>::sse_encode(index, serializer);
 }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Update{index,value} => { <i32>::sse_encode(4, serializer); <u32>::sse_encode(index, serializer);
<crate::features::timeline::domain::entities::event::EventEntity>::sse_encode(value, serializer);
 }
crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity::Reset{items} => { <i32>::sse_encode(5, serializer); <Vec<crate::features::timeline::domain::entities::event::EventEntity>>::sse_encode(items, serializer);
 }
 _ => { unimplemented!(""); }}
    }
}

impl SseEncode for crate::features::timeline::domain::entities::event::EventEntity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.sender_id, serializer);
        <Option<String>>::sse_encode(self.sender_display_name, serializer);
        <Option<String>>::sse_encode(self.sender_avatar_url, serializer);
        <String>::sse_encode(self.content, serializer);
        <Option<String>>::sse_encode(self.formatted_content, serializer);
        <Option<chrono::DateTime<chrono::Utc>>>::sse_encode(self.timestamp, serializer);
        <bool>::sse_encode(self.is_redacted, serializer);
        <String>::sse_encode(self.event_type, serializer);
        <String>::sse_encode(self.message_type, serializer);
        <String>::sse_encode(self.status, serializer);
        <bool>::sse_encode(self.is_encrypted, serializer);
        <Option<std::collections::HashMap<String, String>>>::sse_encode(self.file_info, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode
    for Vec<crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::features::timeline::domain::entities::event_entity_delta::EventDeltaEntity>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::features::timeline::domain::entities::event::EventEntity> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::features::timeline::domain::entities::event::EventEntity>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(String, String)>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::features::rooms::domain::entities::room::RoomEntity> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::features::rooms::domain::entities::room::RoomEntity>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for crate::features::matrix_client_registry::domain::entities::registry_session::MatrixSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::features::matrix_client_registry::domain::entities::registry_session::ClientSessionEntity>::sse_encode(self.client_session, serializer);
<Option<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity>>::sse_encode(self.user_session, serializer);
<Option<String>>::sse_encode(self.sync_token, serializer);
<Option<crate::features::matrix_client_registry::domain::entities::registry_session::Credentials>>::sse_encode(self.credentials, serializer);}
                }

impl SseEncode for Option<std::collections::HashMap<String, String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <std::collections::HashMap<String, String>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<chrono::DateTime<chrono::Utc>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <chrono::DateTime<chrono::Utc>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode
    for Option<
        crate::features::matrix_client_registry::domain::entities::registry_session::Credentials,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::features::matrix_client_registry::domain::entities::registry_session::Credentials>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity>::sse_encode(value, serializer);
                }}
                }

impl SseEncode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
        <String>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::features::rooms::domain::entities::room::RoomEntity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.room_id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <Option<String>>::sse_encode(self.avatar_url, serializer);
        <Option<String>>::sse_encode(self.last_event_text, serializer);
        <Option<chrono::DateTime<chrono::Utc>>>::sse_encode(
            self.last_event_received_time,
            serializer,
        );
        <bool>::sse_encode(self.is_direct_chat, serializer);
        <bool>::sse_encode(self.is_encrypted, serializer);
        <Option<String>>::sse_encode(self.last_event, serializer);
        <i32>::sse_encode(self.participant_count, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::features::matrix_client_registry::domain::entities::registry_session::UserSessionEntity {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.access_token, serializer);
<Option<String>>::sse_encode(self.refresh_token, serializer);
<String>::sse_encode(self.device_id, serializer);
<String>::sse_encode(self.matrix_user_id, serializer);}
                }

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
