// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/okra_wrap.dart';
import 'dart:async';
import 'dart:convert';
import 'features/matrix_client_registry/domain/entities/registry_session.dart';
import 'features/rooms/domain/entities/room.dart';
import 'features/timeline/domain/entities/event.dart';
import 'features/timeline/domain/entities/event_entity_delta.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiOkraWrapInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -655152125;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'matrix_rust_sdk_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<List<EventDeltaEntity>> crateApiOkraWrapFetchRoomEventsByRoomId({
    required String roomId,
    required String accountId,
  });

  Future<void> crateApiOkraWrapInitApp();

  Future<MatrixSessionEntity> crateApiOkraWrapRegisterMatrixClient({
    required MatrixSessionEntity session,
  });

  Stream<String> crateApiOkraWrapSyncEvents({required String accountId});

  Stream<List<RoomEntity>> crateApiOkraWrapSyncRoomsBySpace({
    required String spaceId,
    required String accountId,
  });

  Stream<int> crateApiOkraWrapTick();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<List<EventDeltaEntity>> crateApiOkraWrapFetchRoomEventsByRoomId({
    required String roomId,
    required String accountId,
  }) {
    final sink = RustStreamSink<List<EventDeltaEntity>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(roomId, serializer);
            sse_encode_String(accountId, serializer);
            sse_encode_StreamSink_list_event_delta_entity_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiOkraWrapFetchRoomEventsByRoomIdConstMeta,
          argValues: [roomId, accountId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOkraWrapFetchRoomEventsByRoomIdConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_room_events_by_room_id",
        argNames: ["roomId", "accountId", "sink"],
      );

  @override
  Future<void> crateApiOkraWrapInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOkraWrapInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOkraWrapInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<MatrixSessionEntity> crateApiOkraWrapRegisterMatrixClient({
    required MatrixSessionEntity session,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_matrix_session_entity(session, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_session_entity,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiOkraWrapRegisterMatrixClientConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOkraWrapRegisterMatrixClientConstMeta =>
      const TaskConstMeta(
        debugName: "register_matrix_client",
        argNames: ["session"],
      );

  @override
  Stream<String> crateApiOkraWrapSyncEvents({required String accountId}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(accountId, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiOkraWrapSyncEventsConstMeta,
          argValues: [accountId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOkraWrapSyncEventsConstMeta => const TaskConstMeta(
    debugName: "sync_events",
    argNames: ["accountId", "sink"],
  );

  @override
  Stream<List<RoomEntity>> crateApiOkraWrapSyncRoomsBySpace({
    required String spaceId,
    required String accountId,
  }) {
    final sink = RustStreamSink<List<RoomEntity>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(spaceId, serializer);
            sse_encode_String(accountId, serializer);
            sse_encode_StreamSink_list_room_entity_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiOkraWrapSyncRoomsBySpaceConstMeta,
          argValues: [spaceId, accountId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOkraWrapSyncRoomsBySpaceConstMeta =>
      const TaskConstMeta(
        debugName: "sync_rooms_by_space",
        argNames: ["spaceId", "accountId", "sink"],
      );

  @override
  Stream<int> crateApiOkraWrapTick() {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_i_32_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiOkraWrapTickConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOkraWrapTickConstMeta =>
      const TaskConstMeta(debugName: "tick", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<EventDeltaEntity>>
  dco_decode_StreamSink_list_event_delta_entity_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<RoomEntity>> dco_decode_StreamSink_list_room_entity_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  Credentials dco_decode_box_autoadd_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_credentials(raw);
  }

  @protected
  EventEntity dco_decode_box_autoadd_event_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_event_entity(raw);
  }

  @protected
  MatrixSessionEntity dco_decode_box_autoadd_matrix_session_entity(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_matrix_session_entity(raw);
  }

  @protected
  UserSessionEntity dco_decode_box_autoadd_user_session_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_user_session_entity(raw);
  }

  @protected
  ClientSessionEntity dco_decode_client_session_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClientSessionEntity(
      homeserver: dco_decode_String(arr[0]),
      sessionPath: dco_decode_String(arr[1]),
      passphrase: dco_decode_String(arr[2]),
    );
  }

  @protected
  Credentials dco_decode_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Credentials_AccessToken(dco_decode_String(raw[1]));
      case 1:
        return Credentials_UserPassword(
          username: dco_decode_String(raw[1]),
          password: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  EventDeltaEntity dco_decode_event_delta_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return EventDeltaEntity_PushFront(
          value: dco_decode_box_autoadd_event_entity(raw[1]),
        );
      case 1:
        return EventDeltaEntity_PushBack(
          value: dco_decode_box_autoadd_event_entity(raw[1]),
        );
      case 2:
        return EventDeltaEntity_Insert(
          index: dco_decode_u_32(raw[1]),
          value: dco_decode_box_autoadd_event_entity(raw[2]),
        );
      case 3:
        return EventDeltaEntity_Remove(index: dco_decode_u_32(raw[1]));
      case 4:
        return EventDeltaEntity_Update(
          index: dco_decode_u_32(raw[1]),
          value: dco_decode_box_autoadd_event_entity(raw[2]),
        );
      case 5:
        return EventDeltaEntity_Reset(
          items: dco_decode_list_event_entity(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  EventEntity dco_decode_event_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return EventEntity(
      id: dco_decode_String(arr[0]),
      senderId: dco_decode_String(arr[1]),
      senderDisplayName: dco_decode_opt_String(arr[2]),
      senderAvatarUrl: dco_decode_opt_String(arr[3]),
      content: dco_decode_String(arr[4]),
      formattedContent: dco_decode_opt_String(arr[5]),
      timestamp: dco_decode_opt_box_autoadd_Chrono_Utc(arr[6]),
      isRedacted: dco_decode_bool(arr[7]),
      eventType: dco_decode_String(arr[8]),
      messageType: dco_decode_String(arr[9]),
      status: dco_decode_String(arr[10]),
      isEncrypted: dco_decode_bool(arr[11]),
      fileInfo: dco_decode_opt_Map_String_String_None(arr[12]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<EventDeltaEntity> dco_decode_list_event_delta_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_event_delta_entity).toList();
  }

  @protected
  List<EventEntity> dco_decode_list_event_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_event_entity).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<RoomEntity> dco_decode_list_room_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_room_entity).toList();
  }

  @protected
  MatrixSessionEntity dco_decode_matrix_session_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MatrixSessionEntity(
      clientSession: dco_decode_client_session_entity(arr[0]),
      userSession: dco_decode_opt_box_autoadd_user_session_entity(arr[1]),
      syncToken: dco_decode_opt_String(arr[2]),
      credentials: dco_decode_opt_box_autoadd_credentials(arr[3]),
    );
  }

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_Map_String_String_None(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  Credentials? dco_decode_opt_box_autoadd_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_credentials(raw);
  }

  @protected
  UserSessionEntity? dco_decode_opt_box_autoadd_user_session_entity(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_user_session_entity(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  RoomEntity dco_decode_room_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RoomEntity(
      roomId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_opt_String(arr[2]),
      lastEventText: dco_decode_opt_String(arr[3]),
      lastEventReceivedTime: dco_decode_opt_box_autoadd_Chrono_Utc(arr[4]),
      isDirectChat: dco_decode_bool(arr[5]),
      isEncrypted: dco_decode_bool(arr[6]),
      lastEvent: dco_decode_opt_String(arr[7]),
      participantCount: dco_decode_i_32(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserSessionEntity dco_decode_user_session_entity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UserSessionEntity(
      accessToken: dco_decode_String(arr[0]),
      refreshToken: dco_decode_opt_String(arr[1]),
      deviceId: dco_decode_String(arr[2]),
      matrixUserId: dco_decode_String(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<EventDeltaEntity>>
  sse_decode_StreamSink_list_event_delta_entity_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<RoomEntity>> sse_decode_StreamSink_list_room_entity_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  Credentials sse_decode_box_autoadd_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_credentials(deserializer));
  }

  @protected
  EventEntity sse_decode_box_autoadd_event_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_event_entity(deserializer));
  }

  @protected
  MatrixSessionEntity sse_decode_box_autoadd_matrix_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_matrix_session_entity(deserializer));
  }

  @protected
  UserSessionEntity sse_decode_box_autoadd_user_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_user_session_entity(deserializer));
  }

  @protected
  ClientSessionEntity sse_decode_client_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_homeserver = sse_decode_String(deserializer);
    var var_sessionPath = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_String(deserializer);
    return ClientSessionEntity(
      homeserver: var_homeserver,
      sessionPath: var_sessionPath,
      passphrase: var_passphrase,
    );
  }

  @protected
  Credentials sse_decode_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return Credentials_AccessToken(var_field0);
      case 1:
        var var_username = sse_decode_String(deserializer);
        var var_password = sse_decode_String(deserializer);
        return Credentials_UserPassword(
          username: var_username,
          password: var_password,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  EventDeltaEntity sse_decode_event_delta_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_value = sse_decode_box_autoadd_event_entity(deserializer);
        return EventDeltaEntity_PushFront(value: var_value);
      case 1:
        var var_value = sse_decode_box_autoadd_event_entity(deserializer);
        return EventDeltaEntity_PushBack(value: var_value);
      case 2:
        var var_index = sse_decode_u_32(deserializer);
        var var_value = sse_decode_box_autoadd_event_entity(deserializer);
        return EventDeltaEntity_Insert(index: var_index, value: var_value);
      case 3:
        var var_index = sse_decode_u_32(deserializer);
        return EventDeltaEntity_Remove(index: var_index);
      case 4:
        var var_index = sse_decode_u_32(deserializer);
        var var_value = sse_decode_box_autoadd_event_entity(deserializer);
        return EventDeltaEntity_Update(index: var_index, value: var_value);
      case 5:
        var var_items = sse_decode_list_event_entity(deserializer);
        return EventDeltaEntity_Reset(items: var_items);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  EventEntity sse_decode_event_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_senderDisplayName = sse_decode_opt_String(deserializer);
    var var_senderAvatarUrl = sse_decode_opt_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_formattedContent = sse_decode_opt_String(deserializer);
    var var_timestamp = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_isRedacted = sse_decode_bool(deserializer);
    var var_eventType = sse_decode_String(deserializer);
    var var_messageType = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    var var_fileInfo = sse_decode_opt_Map_String_String_None(deserializer);
    return EventEntity(
      id: var_id,
      senderId: var_senderId,
      senderDisplayName: var_senderDisplayName,
      senderAvatarUrl: var_senderAvatarUrl,
      content: var_content,
      formattedContent: var_formattedContent,
      timestamp: var_timestamp,
      isRedacted: var_isRedacted,
      eventType: var_eventType,
      messageType: var_messageType,
      status: var_status,
      isEncrypted: var_isEncrypted,
      fileInfo: var_fileInfo,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<EventDeltaEntity> sse_decode_list_event_delta_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventDeltaEntity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_delta_entity(deserializer));
    }
    return ans_;
  }

  @protected
  List<EventEntity> sse_decode_list_event_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventEntity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_entity(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<RoomEntity> sse_decode_list_room_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoomEntity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_room_entity(deserializer));
    }
    return ans_;
  }

  @protected
  MatrixSessionEntity sse_decode_matrix_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientSession = sse_decode_client_session_entity(deserializer);
    var var_userSession = sse_decode_opt_box_autoadd_user_session_entity(
      deserializer,
    );
    var var_syncToken = sse_decode_opt_String(deserializer);
    var var_credentials = sse_decode_opt_box_autoadd_credentials(deserializer);
    return MatrixSessionEntity(
      clientSession: var_clientSession,
      userSession: var_userSession,
      syncToken: var_syncToken,
      credentials: var_credentials,
    );
  }

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_Map_String_String_None(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Credentials? sse_decode_opt_box_autoadd_credentials(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_credentials(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UserSessionEntity? sse_decode_opt_box_autoadd_user_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_user_session_entity(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RoomEntity sse_decode_room_entity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_lastEventText = sse_decode_opt_String(deserializer);
    var var_lastEventReceivedTime = sse_decode_opt_box_autoadd_Chrono_Utc(
      deserializer,
    );
    var var_isDirectChat = sse_decode_bool(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    var var_lastEvent = sse_decode_opt_String(deserializer);
    var var_participantCount = sse_decode_i_32(deserializer);
    return RoomEntity(
      roomId: var_roomId,
      displayName: var_displayName,
      avatarUrl: var_avatarUrl,
      lastEventText: var_lastEventText,
      lastEventReceivedTime: var_lastEventReceivedTime,
      isDirectChat: var_isDirectChat,
      isEncrypted: var_isEncrypted,
      lastEvent: var_lastEvent,
      participantCount: var_participantCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserSessionEntity sse_decode_user_session_entity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_opt_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_matrixUserId = sse_decode_String(deserializer);
    return UserSessionEntity(
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      deviceId: var_deviceId,
      matrixUserId: var_matrixUserId,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_event_delta_entity_Sse(
    RustStreamSink<List<EventDeltaEntity>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_event_delta_entity,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_room_entity_Sse(
    RustStreamSink<List<RoomEntity>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_room_entity,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_credentials(
    Credentials self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credentials(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_event_entity(
    EventEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_event_entity(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_matrix_session_entity(
    MatrixSessionEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_matrix_session_entity(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_user_session_entity(
    UserSessionEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user_session_entity(self, serializer);
  }

  @protected
  void sse_encode_client_session_entity(
    ClientSessionEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.homeserver, serializer);
    sse_encode_String(self.sessionPath, serializer);
    sse_encode_String(self.passphrase, serializer);
  }

  @protected
  void sse_encode_credentials(Credentials self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Credentials_AccessToken(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case Credentials_UserPassword(
        username: final username,
        password: final password,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(username, serializer);
        sse_encode_String(password, serializer);
    }
  }

  @protected
  void sse_encode_event_delta_entity(
    EventDeltaEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case EventDeltaEntity_PushFront(value: final value):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_event_entity(value, serializer);
      case EventDeltaEntity_PushBack(value: final value):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_event_entity(value, serializer);
      case EventDeltaEntity_Insert(index: final index, value: final value):
        sse_encode_i_32(2, serializer);
        sse_encode_u_32(index, serializer);
        sse_encode_box_autoadd_event_entity(value, serializer);
      case EventDeltaEntity_Remove(index: final index):
        sse_encode_i_32(3, serializer);
        sse_encode_u_32(index, serializer);
      case EventDeltaEntity_Update(index: final index, value: final value):
        sse_encode_i_32(4, serializer);
        sse_encode_u_32(index, serializer);
        sse_encode_box_autoadd_event_entity(value, serializer);
      case EventDeltaEntity_Reset(items: final items):
        sse_encode_i_32(5, serializer);
        sse_encode_list_event_entity(items, serializer);
    }
  }

  @protected
  void sse_encode_event_entity(EventEntity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_opt_String(self.senderDisplayName, serializer);
    sse_encode_opt_String(self.senderAvatarUrl, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.formattedContent, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.timestamp, serializer);
    sse_encode_bool(self.isRedacted, serializer);
    sse_encode_String(self.eventType, serializer);
    sse_encode_String(self.messageType, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
    sse_encode_opt_Map_String_String_None(self.fileInfo, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_event_delta_entity(
    List<EventDeltaEntity> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_delta_entity(item, serializer);
    }
  }

  @protected
  void sse_encode_list_event_entity(
    List<EventEntity> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_entity(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_room_entity(
    List<RoomEntity> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_room_entity(item, serializer);
    }
  }

  @protected
  void sse_encode_matrix_session_entity(
    MatrixSessionEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_client_session_entity(self.clientSession, serializer);
    sse_encode_opt_box_autoadd_user_session_entity(
      self.userSession,
      serializer,
    );
    sse_encode_opt_String(self.syncToken, serializer);
    sse_encode_opt_box_autoadd_credentials(self.credentials, serializer);
  }

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_Map_String_String_None(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_credentials(
    Credentials? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_credentials(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_user_session_entity(
    UserSessionEntity? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_user_session_entity(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_room_entity(RoomEntity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_opt_String(self.lastEventText, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(
      self.lastEventReceivedTime,
      serializer,
    );
    sse_encode_bool(self.isDirectChat, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
    sse_encode_opt_String(self.lastEvent, serializer);
    sse_encode_i_32(self.participantCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_session_entity(
    UserSessionEntity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accessToken, serializer);
    sse_encode_opt_String(self.refreshToken, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.matrixUserId, serializer);
  }
}
