// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/okra_wrap.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/praia_matrix/features/matrix_client_registry/domain/entities/registry_session.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw);

  @protected
  RustStreamSink<List<EventDeltaEntity>>
  dco_decode_StreamSink_list_event_delta_entity_Sse(dynamic raw);

  @protected
  RustStreamSink<List<RoomEntity>> dco_decode_StreamSink_list_room_entity_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ClientSessionEntity dco_decode_box_autoadd_client_session_entity(dynamic raw);

  @protected
  Credentials dco_decode_box_autoadd_credentials(dynamic raw);

  @protected
  EventEntity dco_decode_box_autoadd_event_entity(dynamic raw);

  @protected
  MatrixSessionEntity dco_decode_box_autoadd_matrix_session_entity(dynamic raw);

  @protected
  UserSessionEntity dco_decode_box_autoadd_user_session_entity(dynamic raw);

  @protected
  ClientSessionEntity dco_decode_client_session_entity(dynamic raw);

  @protected
  Credentials dco_decode_credentials(dynamic raw);

  @protected
  EventDeltaEntity dco_decode_event_delta_entity(dynamic raw);

  @protected
  EventEntity dco_decode_event_entity(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<EventDeltaEntity> dco_decode_list_event_delta_entity(dynamic raw);

  @protected
  List<EventEntity> dco_decode_list_event_entity(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RoomEntity> dco_decode_list_room_entity(dynamic raw);

  @protected
  MatrixSessionEntity dco_decode_matrix_session_entity(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  Credentials? dco_decode_opt_box_autoadd_credentials(dynamic raw);

  @protected
  UserSessionEntity? dco_decode_opt_box_autoadd_user_session_entity(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RoomEntity dco_decode_room_entity(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserSessionEntity dco_decode_user_session_entity(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<EventDeltaEntity>>
  sse_decode_StreamSink_list_event_delta_entity_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<RoomEntity>> sse_decode_StreamSink_list_room_entity_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ClientSessionEntity sse_decode_box_autoadd_client_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  Credentials sse_decode_box_autoadd_credentials(SseDeserializer deserializer);

  @protected
  EventEntity sse_decode_box_autoadd_event_entity(SseDeserializer deserializer);

  @protected
  MatrixSessionEntity sse_decode_box_autoadd_matrix_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  UserSessionEntity sse_decode_box_autoadd_user_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  ClientSessionEntity sse_decode_client_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  Credentials sse_decode_credentials(SseDeserializer deserializer);

  @protected
  EventDeltaEntity sse_decode_event_delta_entity(SseDeserializer deserializer);

  @protected
  EventEntity sse_decode_event_entity(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<EventDeltaEntity> sse_decode_list_event_delta_entity(
    SseDeserializer deserializer,
  );

  @protected
  List<EventEntity> sse_decode_list_event_entity(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<RoomEntity> sse_decode_list_room_entity(SseDeserializer deserializer);

  @protected
  MatrixSessionEntity sse_decode_matrix_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Credentials? sse_decode_opt_box_autoadd_credentials(
    SseDeserializer deserializer,
  );

  @protected
  UserSessionEntity? sse_decode_opt_box_autoadd_user_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RoomEntity sse_decode_room_entity(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserSessionEntity sse_decode_user_session_entity(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_event_delta_entity_Sse(
    RustStreamSink<List<EventDeltaEntity>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_room_entity_Sse(
    RustStreamSink<List<RoomEntity>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_client_session_entity(
    ClientSessionEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_credentials(
    Credentials self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_event_entity(
    EventEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_matrix_session_entity(
    MatrixSessionEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_session_entity(
    UserSessionEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_session_entity(
    ClientSessionEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credentials(Credentials self, SseSerializer serializer);

  @protected
  void sse_encode_event_delta_entity(
    EventDeltaEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event_entity(EventEntity self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_delta_entity(
    List<EventDeltaEntity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_event_entity(
    List<EventEntity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_entity(
    List<RoomEntity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matrix_session_entity(
    MatrixSessionEntity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_credentials(
    Credentials? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_user_session_entity(
    UserSessionEntity? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_entity(RoomEntity self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_session_entity(
    UserSessionEntity self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
