// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EventEntity {
  final String id;
  final String senderId;
  final String? senderDisplayName;
  final String? senderAvatarUrl;
  final String content;
  final String? formattedContent;
  final DateTime? timestamp;
  final bool isRedacted;
  final String eventType;
  final String messageType;
  final String status;
  final bool isEncrypted;
  final Map<String, String>? fileInfo;

  const EventEntity({
    required this.id,
    required this.senderId,
    this.senderDisplayName,
    this.senderAvatarUrl,
    required this.content,
    this.formattedContent,
    this.timestamp,
    required this.isRedacted,
    required this.eventType,
    required this.messageType,
    required this.status,
    required this.isEncrypted,
    this.fileInfo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderDisplayName.hashCode ^
      senderAvatarUrl.hashCode ^
      content.hashCode ^
      formattedContent.hashCode ^
      timestamp.hashCode ^
      isRedacted.hashCode ^
      eventType.hashCode ^
      messageType.hashCode ^
      status.hashCode ^
      isEncrypted.hashCode ^
      fileInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderDisplayName == other.senderDisplayName &&
          senderAvatarUrl == other.senderAvatarUrl &&
          content == other.content &&
          formattedContent == other.formattedContent &&
          timestamp == other.timestamp &&
          isRedacted == other.isRedacted &&
          eventType == other.eventType &&
          messageType == other.messageType &&
          status == other.status &&
          isEncrypted == other.isEncrypted &&
          fileInfo == other.fileInfo;
}
