// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'event.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'event_entity_delta.freezed.dart';

@freezed
sealed class EventDeltaEntity with _$EventDeltaEntity {
  const EventDeltaEntity._();

  const factory EventDeltaEntity.pushFront({required EventEntity value}) =
      EventDeltaEntity_PushFront;
  const factory EventDeltaEntity.pushBack({required EventEntity value}) =
      EventDeltaEntity_PushBack;
  const factory EventDeltaEntity.insert({
    required int index,
    required EventEntity value,
  }) = EventDeltaEntity_Insert;
  const factory EventDeltaEntity.remove({required int index}) =
      EventDeltaEntity_Remove;
  const factory EventDeltaEntity.update({
    required int index,
    required EventEntity value,
  }) = EventDeltaEntity_Update;
  const factory EventDeltaEntity.reset({required List<EventEntity> items}) =
      EventDeltaEntity_Reset;
}
