// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../features/matrix_client_registry/domain/entities/registry_session.dart';
import '../features/rooms/domain/entities/room.dart';
import '../features/timeline/domain/entities/event.dart';
import '../features/timeline/domain/entities/event_entity_delta.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `global_app`, `init`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppContext`

Future<MatrixSessionEntity> registerMatrixClient({
  required MatrixSessionEntity session,
}) =>
    RustLib.instance.api.crateApiOkraWrapRegisterMatrixClient(session: session);

Stream<String> syncEvents({required String accountId}) =>
    RustLib.instance.api.crateApiOkraWrapSyncEvents(accountId: accountId);

Stream<List<RoomEntity>> syncRoomsBySpace({
  required String spaceId,
  required String accountId,
}) => RustLib.instance.api.crateApiOkraWrapSyncRoomsBySpace(
  spaceId: spaceId,
  accountId: accountId,
);

Stream<List<EventDeltaEntity>> fetchRoomEventsByRoomId({
  required String roomId,
  required String accountId,
}) => RustLib.instance.api.crateApiOkraWrapFetchRoomEventsByRoomId(
  roomId: roomId,
  accountId: accountId,
);

Stream<int> tick() => RustLib.instance.api.crateApiOkraWrapTick();
